<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Description>In-process and pipe-based host startup event logging.</Description>
    <Version>0.1.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DevTools.HostLogging.Runner" />
    <InternalsVisibleTo Include="DevTools.HostLogging.Sharp.Tests" />
  </ItemGroup>

</Project>
