<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Avalonia.App</RootNamespace>
    <AssemblyName>Avalonia.App</AssemblyName>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DevTools.ScreenShot.Avalonia.Sharp\DevTools.ScreenShot.Avalonia.Sharp.csproj" />
    <ProjectReference Include="..\Avalonia.Views\Avalonia.Views.csproj" />
    <ProjectReference Include="..\Sample.ViewModels\Sample.ViewModels.csproj" />
  </ItemGroup>

</Project>
