<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Avalonia.Views</RootNamespace>
    <AssemblyName>Avalonia.Views</AssemblyName>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DevKit.Screenshot.Avalonia.Sharp\DevKit.Screenshot.Avalonia.Sharp.csproj" />
    <ProjectReference Include="..\Sample.ViewModels\Sample.ViewModels.csproj" />
  </ItemGroup>

</Project>
